app/controllers/UserAddressController.php
<?php
/**
 * Copyright (c) 8.2017
 * @author Mihail Ivchenko <awrgroup@gmail.com>
 */

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\UserAddress;
use app\models\search\UserAddressSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserAddressController implements the CRUD actions for UserAddress model.
 */
class UserAddressController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserAddress models.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionIndex()
    {
        $searchModel = new UserAddressSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'userID' => Yii::$app->request->getQueryParam('user_id'),
        ]);
    }

    /**
     * Creates a new UserAddress model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionCreate()
    {
        $model = new UserAddress();

        $userModel = User::findOne(Yii::$app->request->getQueryParam('user_id'));

        if(!$userModel) {
            throw new NotFoundHttpException('user not found');
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/user/view', 'id' => $userModel->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'userModel' => $userModel,
        ]);
    }

    /**
     * Deletes an existing UserAddress model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();

        return $this->redirect(['/user/view', 'id' => $model->user_id]);
    }

    /**
     * Finds the UserAddress model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserAddress the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserAddress::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/controllers/UserController.php
<?php
/**
 * Copyright (c) 8.2017
 * @author Mihail Ivchenko <awrgroup@gmail.com>
 */

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\search\UserSearch;
use app\models\search\UserAddressSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    /**
     * Lists all User models.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionView($id)
    {
        $searchModelUserAddress = new UserAddressSearch();
        $dataProviderUserAddress = $searchModelUserAddress->search(Yii::$app->request->queryParams);
        $dataProviderUserAddress->query->andFilterWhere(['user_id' => $id]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModelUserAddress' => $searchModelUserAddress,
            'dataProviderUserAddress' => $dataProviderUserAddress,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $searchModelUserAddress = new UserAddressSearch();
        $dataProviderUserAddress = $searchModelUserAddress->search(Yii::$app->request->queryParams);
        $dataProviderUserAddress->query->andFilterWhere(['user_id' => $id]);

        return $this->render('update', [
            'model' => $model,
            'searchModelUserAddress' => $searchModelUserAddress,
            'dataProviderUserAddress' => $dataProviderUserAddress,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/views/user-address/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserAddress */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="user-address-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'user_id')->hiddenInput(['value'=> Yii::$app->request->getQueryParam('user_id')])->label(false) ?>
    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'comment')->textarea() ?>
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

app/views/user-address/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UserAddress */
/* @var $userModel app\models\User */

$this->title = 'Добавление адреса для пользователя #' . $userModel->id;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = ['label' => 'Адреса пользователя #' . $userModel->id, 'url' => ['/user/view', 'id' => $userModel->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-address-create">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

app/views/user-address/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\UserAddressSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $userID integer */
?>
<div class="user-address-index">
    <h1><?= Html::encode('Адреса пользователя') ?></h1>
    <?php Pjax::begin(); ?>
    <p><?= Html::a('Добавить адрес', ['/user-address/create', 'user_id' => $userID], ['class' => 'btn btn-success']) ?></p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'attribute' => 'address',
                'contentOptions' => ['style'=>'max-width: 200px;']
            ],
            'comment',
            [
                'attribute' => 'created_at',
                'contentOptions' => ['style' => 'width: 160px;']
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
                'urlCreator' => function($action, $model, $key, $index) {
                    return Yii::$app->urlManager->createUrl(['/user-address/' . $action, 'id' => $key]);
                },
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

app/views/user-address/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UserAddress */

$this->title = 'Изменение адреса пользователя: #' . $model->user->id;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = ['label' => 'Пользователь #' . $model->user->id, 'url' => ['/user/view', 'id' => $model->user->id]];
$this->params['breadcrumbs'][] = ['label' => 'Адрес #' . $model->id];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="user-address-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>